/*
 * File: app/store/PlayerStore.js
 * Date: Mon Oct 10 2011 00:45:39 GMT-0400 (EDT)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.PlayerStore', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            storeId: 'PlayerStore',
            proxy: {
                type: 'ajax',
                url: 'data/onlyqb.json',
                reader: {
                    type: 'json',
                    root: 'dynastyui/data'
                }
            },
            fields: [
                {
                    name: 'name'
                },
                {
                    name: 'position'
                },
                {
                    name: 'comp'
                },
                {
                    name: 'pass_yards'
                },
                {
                    name: 'pass_td'
                },
                {
                    name: 'rating'
                },
                {
                    name: 'interceptions'
                },
                {
                    name: 'sacks'
                },
                {
                    name: 'rush_yards'
                },
                {
                    name: 'rush_td'
                },
                {
                    name: 'fan_points'
                },
                {
                    defaultValue: 0
,
                    name: 'salary'
                }
            ]
        }, cfg)]);
    }
});