/*
 * File: app/view/DynastyViewport.js
 * Date: Thu Oct 06 2011 11:53:09 GMT-0400 (EDT)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('MyApp.view.DynastyViewport', {
    extend: 'MyApp.view.ui.DynastyViewport',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    }
});