/*
 * File: designer.js
 * Date: Mon Oct 10 2011 11:48:09 GMT-0400 (EDT)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    name: 'MyApp',

    stores: [
        'PlayerStore',
        'PlayerStoreCharts',
        'DropStore'
    ],

    launch: function() {
        Ext.QuickTips.init();

        var cmp1 = Ext.create('MyApp.view.DynastyViewport', {
            renderTo: Ext.getBody()
        });
        cmp1.show();
    }
});
