#!/usr/bin/env ruby
require File.expand_path('../../config/environment',  __FILE__)

Juggernaut.subscribe do |event, data|
    puts "Subscription request: event(#{event.inspect}) data:(#{data.inspect})"
    data.default = {}
    uuid = data['meta']['id']
    next unless uuid

    team = Team.find_by_uuid(uuid)
    case event
    when :subscribe then team.sessions.increment
    when :unsubscribe then team.sessions.decrement if team.sessions.value > 0
    end
    puts team.sessions.value
end
