#!/usr/bin/env ruby
require File.expand_path('../../config/environment',  __FILE__)

# TODO: This "solution" to dump our session count isn't preferable. If this job crashes and is able to recover, we don't want to flush these.
puts 'Flushing Juggernaut clients'
JuggernautClient.all.each{ |client| client.destroy }

puts 'Starting Juggernaut client listener'
JuggernautClient.subscribe
