/*
 * File: app/view/ui/DynastyViewport.js
 * Date: Mon Oct 10 2011 11:48:09 GMT-0400 (EDT)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ui.DynastyViewport', {
    extend: 'Ext.container.Viewport',

    padding: 10,
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;
        me.items = [
            {
                xtype: 'panel',
                draggable: true,
                maintainFlex: true,
                layout: {
                    type: 'border'
                },
                closeAction: 'hide',
                collapseDirection: 'top',
                collapsible: true,
                overlapHeader: true,
                title: 'Dynasty Owner Draft',
                titleCollapse: true,
                region: 'center',
                items: [
                    {
                        xtype: 'container',
                        height: 80,
                        layout: {
                            align: 'stretch',
                            type: 'hbox'
                        },
                        region: 'north',
                        split: true,
                        items: [
                            {
                                xtype: 'image',
                                src: 'images/dynasty_logo.png'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        layout: {
                            type: 'border'
                        },
                        collapseFirst: false,
                        collapsed: false,
                        region: 'center',
                        items: [
                            {
                                xtype: 'tabpanel',
                                activeTab: 0,
                                region: 'center',
                                items: [
                                    {
                                        xtype: 'gridpanel',
                                        padding: '',
                                        autoScroll: true,
                                        overlapHeader: true,
                                        title: 'Players',
                                        store: 'PlayerStore',
                                        columnLines: true,
                                        viewConfig: {
                                            plugins: [
                                                Ext.create('Ext.grid.plugin.DragDrop', {

                                                })
                                            ]
                                        },
                                        columns: [
                                            {
                                                xtype: 'gridcolumn',
                                                id: 'GridPlayerName',
                                                width: 152,
                                                layout: {
                                                    type: 'fit'
                                                },
                                                dataIndex: 'name',
                                                fixed: true,
                                                groupable: true,
                                                hideable: false,
                                                text: 'Name'
                                            },
                                            {
                                                xtype: 'numbercolumn',
                                                width: 152,
                                                dataIndex: 'fan_points',
                                                text: 'Dynasty Rank'
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                width: 160,
                                                dataIndex: 'rating',
                                                text: 'Rating'
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                id: 'Salary',
                                                width: 149,
                                                dataIndex: 'salary',
                                                text: 'Salary'
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                hidden: true,
                                                dataIndex: 'position',
                                                fixed: true,
                                                text: 'Position'
                                            },
                                            {
                                                xtype: 'numbercolumn',
                                                dataIndex: 'comp',
                                                text: 'Comp'
                                            },
                                            {
                                                xtype: 'numbercolumn',
                                                dataIndex: 'pass_yards',
                                                text: 'Pass Yards'
                                            },
                                            {
                                                xtype: 'numbercolumn',
                                                dataIndex: 'interceptions',
                                                text: 'Interceptions',
                                                format: '0,000'
                                            },
                                            {
                                                xtype: 'numbercolumn',
                                                itemId: 'Rush Yards',
                                                dataIndex: 'rush_yards',
                                                text: 'Rush Yards'
                                            },
                                            {
                                                xtype: 'numbercolumn',
                                                itemId: 'Rush TD',
                                                dataIndex: 'rush_td',
                                                text: 'Rush TD'
                                            }
                                        ],
                                        selModel: Ext.create('Ext.selection.RowModel', {
                                            allowDeselect: true
                                        }),
                                        features: [
                                            {
                                                ftype: 'rowbody'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        layout: {
                                            type: 'fit'
                                        },
                                        title: 'Roster Review',
                                        items: [
                                            {
                                                xtype: 'container',
                                                layout: {
                                                    columns: 2,
                                                    type: 'table'
                                                },
                                                items: [
                                                    {
                                                        xtype: 'gridpanel',
                                                        padding: '',
                                                        width: 600,
                                                        autoScroll: true,
                                                        overlapHeader: true,
                                                        title: 'Roster Review',
                                                        store: 'DropStore',
                                                        columnLines: true,
                                                        viewConfig: {
                                                            plugins: [
                                                                Ext.create('Ext.grid.plugin.DragDrop', {

                                                                })
                                                            ]
                                                        },
                                                        columns: [
                                                            {
                                                                xtype: 'gridcolumn',
                                                                width: 100,
                                                                layout: {
                                                                    type: 'fit'
                                                                },
                                                                dataIndex: 'name',
                                                                fixed: true,
                                                                groupable: true,
                                                                hideable: false,
                                                                text: 'Name'
                                                            },
                                                            {
                                                                xtype: 'gridcolumn',
                                                                id: 'RosterSalary',
                                                                dataIndex: 'salary',
                                                                text: 'Salary'
                                                            },
                                                            {
                                                                xtype: 'numbercolumn',
                                                                itemId: 'Rush TD',
                                                                width: 98,
                                                                dataIndex: 'rush_td',
                                                                text: 'Dynasty Ranking'
                                                            }
                                                        ],
                                                        features: [
                                                            {
                                                                ftype: 'summary'
                                                            }
                                                        ],
                                                        items: [
                                                            {
                                                                xtype: 'button',
                                                                text: 'MyButton'
                                                            },
                                                            {
                                                                xtype: 'menu',
                                                                floating: false,
                                                                width: 120,
                                                                items: [
                                                                    {
                                                                        xtype: 'menuitem',
                                                                        text: 'Menu Item'
                                                                    },
                                                                    {
                                                                        xtype: 'menuitem',
                                                                        text: 'Menu Item'
                                                                    },
                                                                    {
                                                                        xtype: 'menuitem',
                                                                        text: 'Menu Item'
                                                                    }
                                                                ]
                                                            }
                                                        ],
                                                        selModel: Ext.create('Ext.selection.CheckboxModel', {

                                                        })
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        title: 'Recommendation'
                                    },
                                    {
                                        xtype: 'panel',
                                        title: 'Rules'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                width: 250,
                                maintainFlex: true,
                                autoDestroy: false,
                                layout: {
                                    align: 'stretch',
                                    type: 'vbox'
                                },
                                closable: true,
                                closeAction: 'hide',
                                collapseDirection: 'right',
                                collapsed: false,
                                collapsible: true,
                                frameHeader: false,
                                headerPosition: 'left',
                                title: 'DRAFT TOOLBOX',
                                titleCollapse: true,
                                collapseMode: 'header',
                                floatable: false,
                                region: 'east',
                                split: true,
                                items: [
                                    {
                                        xtype: 'gridpanel',
                                        padding: '',
                                        autoScroll: true,
                                        overlapHeader: true,
                                        title: 'Draft Queue',
                                        store: 'DropStore',
                                        columnLines: true,
                                        flex: 1,
                                        viewConfig: {
                                            plugins: [
                                                Ext.create('Ext.grid.plugin.DragDrop', {

                                                })
                                            ]
                                        },
                                        columns: [
                                            {
                                                xtype: 'gridcolumn',
                                                width: 114,
                                                layout: {
                                                    type: 'fit'
                                                },
                                                dataIndex: 'name',
                                                fixed: true,
                                                groupable: true,
                                                hideable: false,
                                                text: 'Name'
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                id: 'DropSalary',
                                                dataIndex: 'salary',
                                                text: 'Salary'
                                            },
                                            {
                                                xtype: 'numbercolumn',
                                                itemId: 'Rush TD',
                                                dataIndex: 'rush_td',
                                                text: 'Rush TD'
                                            }
                                        ],
                                        features: [
                                            {
                                                ftype: 'summary'
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'tabpanel',
                        height: 200,
                        closable: true,
                        closeAction: 'hide',
                        collapseDirection: 'bottom',
                        collapsed: false,
                        collapsible: true,
                        frameHeader: false,
                        hideCollapseTool: true,
                        overlapHeader: true,
                        activeTab: 0,
                        region: 'south',
                        split: true,
                        items: [
                            {
                                xtype: 'panel',
                                activeItem: 0,
                                layout: {
                                    type: 'absolute'
                                },
                                title: 'Chat',
                                items: [
                                    {
                                        xtype: 'textareafield',
                                        border: 2,
                                        height: 100,
                                        margin: '',
                                        padding: 10,
                                        width: 500,
                                        x: 0,
                                        y: 0
                                    },
                                    {
                                        xtype: 'button',
                                        margin: 10,
                                        width: 100,
                                        text: 'Send',
                                        x: 0,
                                        y: 110
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                activeItem: 0,
                                layout: {
                                    type: 'card'
                                },
                                title: 'Recent Drafts'
                            },
                            {
                                xtype: 'panel',
                                activeItem: 0,
                                layout: {
                                    type: 'card'
                                },
                                closable: true,
                                closeAction: 'hide',
                                collapseDirection: 'bottom',
                                collapsed: false,
                                collapsible: true,
                                title: 'Another Option'
                            }
                        ]
                    }
                ]
            }
        ];
        me.callParent(arguments);
    }
});